# Generated by Django 4.0.3 on 2022-05-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Overseas_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='User',
        ),
    ]
